version: "3.8"

services:
  erp-billing-service:
    build: .
    container_name: erp-billing-service
    ports:
      - "8088:8088"
      - "50088:50051"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=billing_db
      - SERVER_PORT=8088
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: billing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
